version: "3.5"
networks: 
  privnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.29.0.0/16
services:
  node1:
    image: temporalx:latest
    network_mode: "host"
    volumes:
      - ./node1:/temporalx
  node2:
    image: temporalx:latest
    network_mode: "host"
    volumes:
      - ./node2:/temporalx
  node3:
    image: temporalx:latest
    network_mode: "host"
    volumes:
      - ./node3:/temporalx
    
